//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.18.0
//     from Assets/Actions/PlayerActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Actions/PlayerActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @PlayerActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @PlayerActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""PlayerActions"",
    ""maps"": [
        {
            ""name"": ""Dissolve"",
            ""id"": ""7b1d4de2-a6d5-4b82-9a6a-e2a971774a80"",
            ""actions"": [
                {
                    ""name"": ""Dissolve"",
                    ""type"": ""Button"",
                    ""id"": ""89f2e7e0-223c-497a-94db-e8291826b2b1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reappear"",
                    ""type"": ""Button"",
                    ""id"": ""198811d9-e340-48db-a796-6193391555cc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""55cf0065-5dce-42ed-84c0-d6ce3f437c54"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dissolve"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f73a3f1d-746b-4fd0-b1be-fda9136d7d46"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reappear"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""AStarTest"",
            ""id"": ""fa80fb46-c8b1-4bf8-98c8-e1ab4dd0ab06"",
            ""actions"": [
                {
                    ""name"": ""StartPosition"",
                    ""type"": ""Button"",
                    ""id"": ""4b7d8e4e-db2d-4f24-af02-47c6faef1fe4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EndPosition"",
                    ""type"": ""Button"",
                    ""id"": ""9a73c040-88f5-4fb6-b287-0c537d9d23b4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DrawPath"",
                    ""type"": ""Button"",
                    ""id"": ""7a4bb38f-6d07-4245-93e6-8fd43503687c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AddObstacles"",
                    ""type"": ""Button"",
                    ""id"": ""003d4337-5202-46fc-b5b9-336c122f937f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""053cc943-b6cc-4009-89d9-71162db54cdd"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StartPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b05311b4-37ec-4fbb-b308-17c05cb9a630"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EndPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""90d587b2-7674-4f6c-b82d-9e40d84ec5eb"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DrawPath"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd12f432-5207-4b37-8270-c30a34afa282"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AddObstacles"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Dissolve
        m_Dissolve = asset.FindActionMap("Dissolve", throwIfNotFound: true);
        m_Dissolve_Dissolve = m_Dissolve.FindAction("Dissolve", throwIfNotFound: true);
        m_Dissolve_Reappear = m_Dissolve.FindAction("Reappear", throwIfNotFound: true);
        // AStarTest
        m_AStarTest = asset.FindActionMap("AStarTest", throwIfNotFound: true);
        m_AStarTest_StartPosition = m_AStarTest.FindAction("StartPosition", throwIfNotFound: true);
        m_AStarTest_EndPosition = m_AStarTest.FindAction("EndPosition", throwIfNotFound: true);
        m_AStarTest_DrawPath = m_AStarTest.FindAction("DrawPath", throwIfNotFound: true);
        m_AStarTest_AddObstacles = m_AStarTest.FindAction("AddObstacles", throwIfNotFound: true);
    }

    ~@PlayerActions()
    {
        UnityEngine.Debug.Assert(!m_Dissolve.enabled, "This will cause a leak and performance issues, PlayerActions.Dissolve.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_AStarTest.enabled, "This will cause a leak and performance issues, PlayerActions.AStarTest.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Dissolve
    private readonly InputActionMap m_Dissolve;
    private List<IDissolveActions> m_DissolveActionsCallbackInterfaces = new List<IDissolveActions>();
    private readonly InputAction m_Dissolve_Dissolve;
    private readonly InputAction m_Dissolve_Reappear;
    /// <summary>
    /// Provides access to input actions defined in input action map "Dissolve".
    /// </summary>
    public struct DissolveActions
    {
        private @PlayerActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public DissolveActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Dissolve/Dissolve".
        /// </summary>
        public InputAction @Dissolve => m_Wrapper.m_Dissolve_Dissolve;
        /// <summary>
        /// Provides access to the underlying input action "Dissolve/Reappear".
        /// </summary>
        public InputAction @Reappear => m_Wrapper.m_Dissolve_Reappear;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Dissolve; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="DissolveActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(DissolveActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="DissolveActions" />
        public void AddCallbacks(IDissolveActions instance)
        {
            if (instance == null || m_Wrapper.m_DissolveActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DissolveActionsCallbackInterfaces.Add(instance);
            @Dissolve.started += instance.OnDissolve;
            @Dissolve.performed += instance.OnDissolve;
            @Dissolve.canceled += instance.OnDissolve;
            @Reappear.started += instance.OnReappear;
            @Reappear.performed += instance.OnReappear;
            @Reappear.canceled += instance.OnReappear;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="DissolveActions" />
        private void UnregisterCallbacks(IDissolveActions instance)
        {
            @Dissolve.started -= instance.OnDissolve;
            @Dissolve.performed -= instance.OnDissolve;
            @Dissolve.canceled -= instance.OnDissolve;
            @Reappear.started -= instance.OnReappear;
            @Reappear.performed -= instance.OnReappear;
            @Reappear.canceled -= instance.OnReappear;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="DissolveActions.UnregisterCallbacks(IDissolveActions)" />.
        /// </summary>
        /// <seealso cref="DissolveActions.UnregisterCallbacks(IDissolveActions)" />
        public void RemoveCallbacks(IDissolveActions instance)
        {
            if (m_Wrapper.m_DissolveActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="DissolveActions.AddCallbacks(IDissolveActions)" />
        /// <seealso cref="DissolveActions.RemoveCallbacks(IDissolveActions)" />
        /// <seealso cref="DissolveActions.UnregisterCallbacks(IDissolveActions)" />
        public void SetCallbacks(IDissolveActions instance)
        {
            foreach (var item in m_Wrapper.m_DissolveActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DissolveActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="DissolveActions" /> instance referencing this action map.
    /// </summary>
    public DissolveActions @Dissolve => new DissolveActions(this);

    // AStarTest
    private readonly InputActionMap m_AStarTest;
    private List<IAStarTestActions> m_AStarTestActionsCallbackInterfaces = new List<IAStarTestActions>();
    private readonly InputAction m_AStarTest_StartPosition;
    private readonly InputAction m_AStarTest_EndPosition;
    private readonly InputAction m_AStarTest_DrawPath;
    private readonly InputAction m_AStarTest_AddObstacles;
    /// <summary>
    /// Provides access to input actions defined in input action map "AStarTest".
    /// </summary>
    public struct AStarTestActions
    {
        private @PlayerActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public AStarTestActions(@PlayerActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "AStarTest/StartPosition".
        /// </summary>
        public InputAction @StartPosition => m_Wrapper.m_AStarTest_StartPosition;
        /// <summary>
        /// Provides access to the underlying input action "AStarTest/EndPosition".
        /// </summary>
        public InputAction @EndPosition => m_Wrapper.m_AStarTest_EndPosition;
        /// <summary>
        /// Provides access to the underlying input action "AStarTest/DrawPath".
        /// </summary>
        public InputAction @DrawPath => m_Wrapper.m_AStarTest_DrawPath;
        /// <summary>
        /// Provides access to the underlying input action "AStarTest/AddObstacles".
        /// </summary>
        public InputAction @AddObstacles => m_Wrapper.m_AStarTest_AddObstacles;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_AStarTest; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="AStarTestActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(AStarTestActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="AStarTestActions" />
        public void AddCallbacks(IAStarTestActions instance)
        {
            if (instance == null || m_Wrapper.m_AStarTestActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_AStarTestActionsCallbackInterfaces.Add(instance);
            @StartPosition.started += instance.OnStartPosition;
            @StartPosition.performed += instance.OnStartPosition;
            @StartPosition.canceled += instance.OnStartPosition;
            @EndPosition.started += instance.OnEndPosition;
            @EndPosition.performed += instance.OnEndPosition;
            @EndPosition.canceled += instance.OnEndPosition;
            @DrawPath.started += instance.OnDrawPath;
            @DrawPath.performed += instance.OnDrawPath;
            @DrawPath.canceled += instance.OnDrawPath;
            @AddObstacles.started += instance.OnAddObstacles;
            @AddObstacles.performed += instance.OnAddObstacles;
            @AddObstacles.canceled += instance.OnAddObstacles;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="AStarTestActions" />
        private void UnregisterCallbacks(IAStarTestActions instance)
        {
            @StartPosition.started -= instance.OnStartPosition;
            @StartPosition.performed -= instance.OnStartPosition;
            @StartPosition.canceled -= instance.OnStartPosition;
            @EndPosition.started -= instance.OnEndPosition;
            @EndPosition.performed -= instance.OnEndPosition;
            @EndPosition.canceled -= instance.OnEndPosition;
            @DrawPath.started -= instance.OnDrawPath;
            @DrawPath.performed -= instance.OnDrawPath;
            @DrawPath.canceled -= instance.OnDrawPath;
            @AddObstacles.started -= instance.OnAddObstacles;
            @AddObstacles.performed -= instance.OnAddObstacles;
            @AddObstacles.canceled -= instance.OnAddObstacles;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="AStarTestActions.UnregisterCallbacks(IAStarTestActions)" />.
        /// </summary>
        /// <seealso cref="AStarTestActions.UnregisterCallbacks(IAStarTestActions)" />
        public void RemoveCallbacks(IAStarTestActions instance)
        {
            if (m_Wrapper.m_AStarTestActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="AStarTestActions.AddCallbacks(IAStarTestActions)" />
        /// <seealso cref="AStarTestActions.RemoveCallbacks(IAStarTestActions)" />
        /// <seealso cref="AStarTestActions.UnregisterCallbacks(IAStarTestActions)" />
        public void SetCallbacks(IAStarTestActions instance)
        {
            foreach (var item in m_Wrapper.m_AStarTestActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_AStarTestActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="AStarTestActions" /> instance referencing this action map.
    /// </summary>
    public AStarTestActions @AStarTest => new AStarTestActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Dissolve" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="DissolveActions.AddCallbacks(IDissolveActions)" />
    /// <seealso cref="DissolveActions.RemoveCallbacks(IDissolveActions)" />
    public interface IDissolveActions
    {
        /// <summary>
        /// Method invoked when associated input action "Dissolve" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDissolve(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Reappear" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnReappear(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "AStarTest" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="AStarTestActions.AddCallbacks(IAStarTestActions)" />
    /// <seealso cref="AStarTestActions.RemoveCallbacks(IAStarTestActions)" />
    public interface IAStarTestActions
    {
        /// <summary>
        /// Method invoked when associated input action "StartPosition" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnStartPosition(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "EndPosition" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnEndPosition(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "DrawPath" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDrawPath(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "AddObstacles" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnAddObstacles(InputAction.CallbackContext context);
    }
}
